<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>KurabeteNotebook</AssemblyName>
    <RootNamespace>KurabeteNotebook.App</RootNamespace>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\KurabeteNotebook.Core\KurabeteNotebook.Core.csproj" />
    <ProjectReference Include="..\KurabeteNotebook.Data\KurabeteNotebook.Data.csproj" />
  </ItemGroup>
</Project>
